// Generated by scripts/generate-content.mjs. Do not edit by hand.
export const articles = [
  {
    "title": "Python là gì?",
    "description": "Bức tranh tổng quan về Python, điểm mạnh và cách chọn nó cho một dự án thực tế.",
    "slug": "/bat-dau/python-la-gi",
    "category": "getting-started",
    "categoryLabel": "Bắt đầu",
    "order": 10,
    "difficulty": "beginner",
    "keywords": [
      "python",
      "ngôn ngữ lập trình",
      "học python",
      "python dùng để làm gì"
    ],
    "updated": "2026-09-18",
    "related": [
      "/bat-dau/cai-dat-python",
      "/bat-dau/hello-world",
      "/co-ban/bien"
    ],
    "body": "Python là một ngôn ngữ lập trình cấp cao, đa mục đích và ưu tiên khả năng đọc. Cú pháp của Python thường gần với cách con người diễn đạt ý tưởng, vì vậy bạn có thể tập trung vào bài toán thay vì viết nhiều mã lặp.\n\n## Python phù hợp với việc gì?\n\nPython được dùng trong web backend, tự động hóa, dữ liệu, AI, kiểm thử, công cụ dòng lệnh và giáo dục. Hệ sinh thái phong phú giúp một ý tưởng nhỏ có thể phát triển thành sản phẩm mà không phải đổi ngôn ngữ quá sớm.\n\n## Một chương trình Python trông như thế nào?\n\n```python\nfrom pathlib import Path\n\nproject = Path(\"reports\")\nprint(f\"Đang làm việc với thư mục: {project.resolve()}\")\n```\n\nĐiểm đáng chú ý là code không cần dấu ngoặc nhọn để biểu diễn khối lệnh. Thụt đầu dòng là một phần của cú pháp, giúp cấu trúc chương trình dễ nhìn hơn.\n\n## Khi nào nên chọn Python?\n\nChọn Python khi tốc độ phát triển, khả năng đọc và thư viện sẵn có quan trọng. Với ứng dụng đòi hỏi độ trễ cực thấp, chạy trên thiết bị rất hạn chế hoặc cần kiểm soát bộ nhớ tuyệt đối, bạn có thể cần cân nhắc thêm ngôn ngữ khác.\n\n## Lộ trình đọc tiếp\n\nBắt đầu bằng cách cài Python, chạy chương trình đầu tiên, sau đó học biến và các kiểu dữ liệu. Khi đã quen với cú pháp, hãy chuyển sang điều khiển luồng và hàm.",
    "source": "content/python/getting-started/python-la-gi.md",
    "headings": [
      {
        "title": "Python phù hợp với việc gì?",
        "id": "python-phu-hop-voi-viec-gi"
      },
      {
        "title": "Một chương trình Python trông như thế nào?",
        "id": "mot-chuong-trinh-python-trong-nhu-the-nao"
      },
      {
        "title": "Khi nào nên chọn Python?",
        "id": "khi-nao-nen-chon-python"
      },
      {
        "title": "Lộ trình đọc tiếp",
        "id": "lo-trinh-oc-tiep"
      }
    ]
  },
  {
    "title": "Cài đặt Python",
    "description": "Cài Python hiện đại, kiểm tra phiên bản và chuẩn bị môi trường làm việc sạch.",
    "slug": "/bat-dau/cai-dat-python",
    "category": "getting-started",
    "categoryLabel": "Bắt đầu",
    "order": 20,
    "difficulty": "beginner",
    "keywords": [
      "cài python",
      "python 3",
      "python windows",
      "python macos",
      "python linux"
    ],
    "updated": "2026-09-18",
    "related": [
      "/bat-dau/python-la-gi",
      "/bat-dau/hello-world",
      "/bat-dau/virtual-environment"
    ],
    "body": "Hãy ưu tiên phiên bản Python 3 đang được hỗ trợ. Sau khi cài, kiểm tra bằng lệnh `python --version` hoặc `python3 --version` tùy hệ điều hành.\n\n## Kiểm tra trình thông dịch\n\n```bash\npython --version\npython -c \"import sys; print(sys.executable)\"\n```\n\nLệnh thứ hai cho biết chính xác executable nào đang được gọi. Đây là cách nhanh để phát hiện việc máy có nhiều bản Python.\n\n## Chuẩn bị project\n\nMỗi project nên có môi trường ảo riêng. Từ thư mục project, chạy:\n\n```bash\npython -m venv .venv\n```\n\nKích hoạt môi trường ảo trước khi cài thư viện. Trên Windows dùng `.venv\\\\Scripts\\\\activate`, còn macOS/Linux dùng `source .venv/bin/activate`.\n\n## Lỗi thường gặp\n\nNếu lệnh `python` không tồn tại, thử `python3` hoặc kiểm tra PATH. Đừng sửa PATH một cách mù quáng khi máy có nhiều bản Python; hãy xác định executable bằng `sys.executable` trước.",
    "source": "content/python/getting-started/cai-dat-python.md",
    "headings": [
      {
        "title": "Kiểm tra trình thông dịch",
        "id": "kiem-tra-trinh-thong-dich"
      },
      {
        "title": "Chuẩn bị project",
        "id": "chuan-bi-project"
      },
      {
        "title": "Lỗi thường gặp",
        "id": "loi-thuong-gap"
      }
    ]
  },
  {
    "title": "Hello World và cách chạy file .py",
    "description": "Viết, lưu và chạy chương trình Python đầu tiên từ terminal hoặc IDE.",
    "slug": "/bat-dau/hello-world",
    "category": "getting-started",
    "categoryLabel": "Bắt đầu",
    "order": 30,
    "difficulty": "beginner",
    "keywords": [
      "hello world",
      "chạy file py",
      "python script",
      "print"
    ],
    "updated": "2026-09-18",
    "related": [
      "/bat-dau/cai-dat-python",
      "/co-ban/string"
    ],
    "body": "Tạo file `hello.py` và đặt một chương trình nhỏ có đầu ra rõ ràng:\n\n```python\nname = \"Nam\"\nprint(f\"Xin chào, {name}!\")\n```\n\nChạy file từ thư mục chứa nó:\n\n```bash\npython hello.py\n```\n\n## Vì sao nên chạy từ terminal?\n\nTerminal cho bạn biết chính xác interpreter, thư mục hiện tại và tham số truyền vào. Đây là nền tảng tốt trước khi dùng IDE hoặc hệ thống build.\n\n## REPL\n\nChạy `python` không kèm tên file để mở REPL, nơi phù hợp để thử nhanh một biểu thức:\n\n```python\n>>> 2 ** 10\n1024\n```\n\nREPL hữu ích để khám phá API, nhưng logic của ứng dụng nên nằm trong file để có thể kiểm thử và review.",
    "source": "content/python/getting-started/hello-world.md",
    "headings": [
      {
        "title": "Vì sao nên chạy từ terminal?",
        "id": "vi-sao-nen-chay-tu-terminal"
      },
      {
        "title": "REPL",
        "id": "repl"
      }
    ]
  },
  {
    "title": "Virtual environment với venv",
    "description": "Tách dependency theo từng project để cài đặt an toàn và tái lập được.",
    "slug": "/bat-dau/virtual-environment",
    "category": "getting-started",
    "categoryLabel": "Bắt đầu",
    "order": 40,
    "difficulty": "beginner",
    "keywords": [
      "venv",
      "virtualenv",
      "môi trường ảo",
      "dependency"
    ],
    "updated": "2026-09-18",
    "related": [
      "/bat-dau/cai-dat-python",
      "/packaging/pip"
    ],
    "body": "Môi trường ảo là một thư mục chứa interpreter và package độc lập với các project khác. Nó tránh tình trạng project A vô tình dùng phiên bản thư viện của project B.\n\n```bash\npython -m venv .venv\npython -m pip install --upgrade pip\npython -m pip install requests\n```\n\nDùng `python -m pip` thay vì gọi `pip` trần giúp chắc chắn pip thuộc đúng interpreter đang hoạt động.\n\n## Đưa môi trường ảo vào workflow\n\nThêm `.venv/` vào `.gitignore`, ghi dependency vào `requirements.txt` hoặc `pyproject.toml`, và hướng dẫn contributor cách tạo lại môi trường. Không commit cả thư mục `.venv` vì nó phụ thuộc hệ điều hành và đường dẫn máy cá nhân.",
    "source": "content/python/getting-started/virtual-environment.md",
    "headings": [
      {
        "title": "Đưa môi trường ảo vào workflow",
        "id": "ua-moi-truong-ao-vao-workflow"
      }
    ]
  },
  {
    "title": "Biến trong Python",
    "description": "Hiểu assignment, tên biến và cách Python gắn tên với object trong bộ nhớ.",
    "slug": "/co-ban/bien",
    "category": "fundamentals",
    "categoryLabel": "Cơ bản",
    "order": 100,
    "difficulty": "beginner",
    "keywords": [
      "biến python",
      "variable",
      "assignment",
      "name binding"
    ],
    "updated": "2026-09-18",
    "related": [
      "/co-ban/kieu-du-lieu",
      "/co-ban/toan-tu",
      "/collection/list"
    ],
    "body": "Trong Python, biến là một cái tên trỏ tới object, không phải chiếc hộp có kiểu cố định. Assignment tạo hoặc cập nhật liên kết đó:\n\n```python\ndeadline_days = 14\ndeadline_days = deadline_days - 2\nprint(deadline_days)  # 12\n```\n\n## Đặt tên\n\nDùng `snake_case` cho biến và hàm, đặt tên thể hiện ý nghĩa: `retry_limit` tốt hơn `n`. Hằng số theo quy ước viết hoa như `DEFAULT_TIMEOUT = 10`.\n\n## Multiple assignment\n\n```python\nwidth, height = 1280, 720\nwidth, height = height, width\n```\n\nPython đánh giá vế phải trước rồi mới gán, nên phép hoán đổi trên không cần biến tạm.\n\n## Dễ nhầm\n\nHai tên có thể trỏ cùng một object. Điều này quan trọng với object mutable như list: `backup = items` không tạo bản sao. Khi cần bản sao, dùng `items.copy()` hoặc `copy.deepcopy()` tùy cấu trúc dữ liệu.",
    "source": "content/python/fundamentals/bien.md",
    "headings": [
      {
        "title": "Đặt tên",
        "id": "at-ten"
      },
      {
        "title": "Multiple assignment",
        "id": "multiple-assignment"
      },
      {
        "title": "Dễ nhầm",
        "id": "de-nham"
      }
    ]
  },
  {
    "title": "Kiểu dữ liệu trong Python",
    "description": "Bản đồ nhanh về số, chuỗi, boolean, None, bytes và chuyển đổi kiểu.",
    "slug": "/co-ban/kieu-du-lieu",
    "category": "data-types",
    "categoryLabel": "Kiểu dữ liệu",
    "order": 110,
    "difficulty": "beginner",
    "keywords": [
      "data types",
      "int",
      "float",
      "str",
      "bool",
      "none",
      "bytes",
      "mutable immutable"
    ],
    "updated": "2026-09-18",
    "related": [
      "/co-ban/bien",
      "/co-ban/toan-tu",
      "/collection/list"
    ],
    "body": "Python có một hệ thống object thống nhất. Một số kiểu nền tảng thường gặp:\n\n```python\ncount = 3                 # int\nratio = 0.75              # float\nenabled = True            # bool\nlabel = \"production\"     # str\npayload = b\"OK\"          # bytes\nmissing = None            # NoneType\n```\n\n## Chuyển đổi kiểu\n\nChuyển đổi tường minh giúp code dễ đọc và tránh bất ngờ từ input luôn là chuỗi:\n\n```python\nraw_port = \"8080\"\nport = int(raw_port)\nassert port > 0\n```\n\n## Mutable và immutable\n\n`int`, `float`, `bool`, `str`, `tuple` là immutable: thao tác “thay đổi” tạo object mới. `list`, `dict`, `set` là mutable và có thể thay đổi tại chỗ. Khi truyền object vào hàm, hãy biết hàm đang mutate hay tạo object mới để tránh side effect.",
    "source": "content/python/data-types/kieu-du-lieu.md",
    "headings": [
      {
        "title": "Chuyển đổi kiểu",
        "id": "chuyen-oi-kieu"
      },
      {
        "title": "Mutable và immutable",
        "id": "mutable-va-immutable"
      }
    ]
  },
  {
    "title": "Toán tử và biểu thức",
    "description": "Các toán tử số học, so sánh, logic và cách viết biểu thức dễ đọc.",
    "slug": "/co-ban/toan-tu",
    "category": "fundamentals",
    "categoryLabel": "Cơ bản",
    "order": 120,
    "difficulty": "beginner",
    "keywords": [
      "operators",
      "expression",
      "arithmetic",
      "comparison",
      "logical operators"
    ],
    "updated": "2026-09-18",
    "related": [
      "/co-ban/bien",
      "/dieu-khien/if-elif-else"
    ],
    "body": "Biểu thức là code tạo ra một giá trị. Toán tử kết hợp các giá trị đó thành logic của chương trình.\n\n```python\nsubtotal = 280_000\ndiscount = 0.1 if subtotal >= 200_000 else 0\ntotal = subtotal * (1 - discount)\n```\n\nCác nhóm chính gồm số học (`+`, `-`, `*`, `/`, `//`, `%`, `**`), so sánh (`==`, `!=`, `<`, `>=`) và logic (`and`, `or`, `not`). Dùng ngoặc khi ưu tiên chưa rõ thay vì dựa vào trí nhớ về precedence.\n\n## `is` và `==`\n\n`==` so sánh giá trị, còn `is` kiểm tra identity. Dùng `is None` để kiểm tra `None`, nhưng không dùng `is` thay cho `==` khi so sánh chuỗi hoặc số.",
    "source": "content/python/fundamentals/toan-tu.md",
    "headings": [
      {
        "title": "`is` và `==`",
        "id": "is-va"
      }
    ]
  },
  {
    "title": "if, elif và else",
    "description": "Rẽ nhánh logic bằng điều kiện rõ ràng, dễ mở rộng và dễ kiểm thử.",
    "slug": "/dieu-khien/if-elif-else",
    "category": "control-flow",
    "categoryLabel": "Điều khiển luồng",
    "order": 200,
    "difficulty": "beginner",
    "keywords": [
      "if",
      "elif",
      "else",
      "điều kiện",
      "conditional"
    ],
    "updated": "2026-09-18",
    "related": [
      "/co-ban/toan-tu",
      "/dieu-khien/for",
      "/dieu-khien/while"
    ],
    "body": "`if` chạy một khối khi điều kiện đúng. `elif` cho các nhánh thay thế và `else` xử lý phần còn lại.\n\n```python\nscore = 82\n\nif score >= 90:\n    level = \"excellent\"\nelif score >= 70:\n    level = \"good\"\nelse:\n    level = \"needs-review\"\n```\n\n## Guard clauses\n\nTrong hàm, trả về sớm cho trường hợp không hợp lệ giúp giảm nesting:\n\n```python\ndef can_publish(is_owner: bool, has_draft: bool) -> bool:\n    if not is_owner or not has_draft:\n        return False\n    return True\n```\n\nĐừng nhồi nhiều điều kiện không liên quan vào một dòng. Nếu điều kiện có tên riêng, hãy tách thành biến boolean hoặc hàm nhỏ.",
    "source": "content/python/control-flow/if-elif-else.md",
    "headings": [
      {
        "title": "Guard clauses",
        "id": "guard-clauses"
      }
    ]
  },
  {
    "title": "Vòng lặp for",
    "description": "Duyệt iterable bằng for, chọn biến vòng lặp rõ nghĩa và tránh thay đổi collection sai cách.",
    "slug": "/dieu-khien/for",
    "category": "control-flow",
    "categoryLabel": "Điều khiển luồng",
    "order": 210,
    "difficulty": "beginner",
    "keywords": [
      "for loop",
      "vòng lặp for",
      "iterable",
      "enumerate",
      "zip"
    ],
    "updated": "2026-09-18",
    "related": [
      "/dieu-khien/range",
      "/collection/list",
      "/ham/function"
    ],
    "body": "`for` duyệt từng phần tử của một iterable. Hãy duyệt trực tiếp collection khi không cần index:\n\n```python\npending = [\"invoice-104\", \"invoice-105\", \"invoice-106\"]\nfor invoice_id in pending:\n    print(f\"Đang xử lý {invoice_id}\")\n```\n\nKhi cần vị trí, dùng `enumerate`; khi ghép hai dãy, dùng `zip`:\n\n```python\nfor position, invoice_id in enumerate(pending, start=1):\n    print(position, invoice_id)\n```\n\nTránh xóa phần tử ngay trên list đang duyệt. Hãy tạo list mới bằng comprehension hoặc lọc trước để không bỏ sót phần tử.",
    "source": "content/python/control-flow/for.md",
    "headings": []
  },
  {
    "title": "Vòng lặp while",
    "description": "Lặp theo điều kiện, quản lý trạng thái và tránh vòng lặp vô hạn.",
    "slug": "/dieu-khien/while",
    "category": "control-flow",
    "categoryLabel": "Điều khiển luồng",
    "order": 220,
    "difficulty": "beginner",
    "keywords": [
      "while loop",
      "vòng lặp while",
      "break",
      "retry"
    ],
    "updated": "2026-09-18",
    "related": [
      "/dieu-khien/for",
      "/dieu-khien/break-continue"
    ],
    "body": "Dùng `while` khi số lần lặp phụ thuộc vào một trạng thái thay đổi dần, chẳng hạn retry đến khi thành công hoặc đọc đến cuối stream.\n\n```python\nattempt = 0\nmax_attempts = 3\nwhile attempt < max_attempts:\n    attempt += 1\n    print(f\"Thử lần {attempt}\")\n```\n\nMọi nhánh dẫn tới lần kiểm tra tiếp theo phải cập nhật trạng thái hoặc kết thúc vòng lặp. Nếu không, chương trình có thể treo vì vòng lặp vô hạn.",
    "source": "content/python/control-flow/while.md",
    "headings": []
  },
  {
    "title": "range trong Python",
    "description": "Tạo dãy số lười bằng range và hiểu start, stop, step.",
    "slug": "/dieu-khien/range",
    "category": "control-flow",
    "categoryLabel": "Điều khiển luồng",
    "order": 230,
    "difficulty": "beginner",
    "keywords": [
      "range",
      "start stop step",
      "dãy số",
      "loop"
    ],
    "updated": "2026-09-18",
    "related": [
      "/dieu-khien/for",
      "/co-ban/bien"
    ],
    "body": "`range` biểu diễn một dãy số theo kiểu lazy, nên không tạo sẵn cả list trong bộ nhớ.\n\n```python\nfor page in range(1, 4):\n    print(f\"Tải trang {page}\")\n\nfor index in range(10, 2, -2):\n    print(index)  # 10, 8, 6, 4\n```\n\nGiá trị `stop` không bao giờ được bao gồm. Nếu bạn chỉ cần duyệt phần tử của collection, ưu tiên duyệt collection trực tiếp thay vì `range(len(items))`.",
    "source": "content/python/control-flow/range.md",
    "headings": []
  },
  {
    "title": "break và continue",
    "description": "Điều khiển sớm vòng lặp và cách giữ logic vòng lặp dễ đọc.",
    "slug": "/dieu-khien/break-continue",
    "category": "control-flow",
    "categoryLabel": "Điều khiển luồng",
    "order": 240,
    "difficulty": "beginner",
    "keywords": [
      "break",
      "continue",
      "loop control",
      "vòng lặp"
    ],
    "updated": "2026-09-18",
    "related": [
      "/dieu-khien/for",
      "/dieu-khien/while"
    ],
    "body": "`break` kết thúc vòng lặp ngay; `continue` bỏ qua phần còn lại của lượt hiện tại và chuyển sang lượt kế tiếp.\n\n```python\nfor event in events:\n    if event is None:\n        continue\n    if event == \"shutdown\":\n        break\n    handle(event)\n```\n\nNếu có quá nhiều `break` và `continue`, hãy tách logic xử lý thành hàm hoặc đổi sang pipeline rõ ràng hơn. `for ... else` cũng có thể diễn đạt “không tìm thấy” mà không cần cờ trạng thái riêng.",
    "source": "content/python/control-flow/break-continue.md",
    "headings": []
  },
  {
    "title": "List trong Python",
    "description": "List cho dữ liệu có thứ tự, có thể thay đổi và thường xuyên cần thêm hoặc lọc phần tử.",
    "slug": "/collection/list",
    "category": "collections",
    "categoryLabel": "Collections",
    "order": 300,
    "difficulty": "beginner",
    "keywords": [
      "list python",
      "collection",
      "indexing",
      "slicing",
      "mutable"
    ],
    "updated": "2026-09-18",
    "related": [
      "/collection/tuple",
      "/collection/dictionary",
      "/co-ban/kieu-du-lieu"
    ],
    "body": "List đại diện cho một dãy phần tử có thứ tự. Nó phù hợp với hàng đợi nhỏ, kết quả truy vấn, danh sách bước xử lý hoặc dữ liệu cần cập nhật.\n\n```python\ntasks = [\"review\", \"test\", \"deploy\"]\nfirst_task = tasks[0]\nlast_two = tasks[-2:]\ntasks.append(\"monitor\")\n```\n\n## Indexing và slicing\n\nIndex bắt đầu từ `0`, index âm đếm từ cuối. Slicing tạo một list mới và dùng quy tắc `start:stop:step`, trong đó `stop` không bao gồm.\n\n## Khi nào không nên dùng list?\n\nNếu cần tra cứu theo khóa, dùng `dict`; cần loại trùng, dùng `set`; cần dữ liệu bất biến, cân nhắc `tuple`. Xóa đầu list nhiều lần có thể chậm; với queue, dùng `collections.deque`.\n\n## Comprehension\n\n```python\nurgent = [task for task in tasks if task in {\"review\", \"deploy\"}]\n```\n\nGiữ comprehension ngắn và đơn giản. Logic nhiều nhánh nên dùng vòng lặp thường để dễ debug.",
    "source": "content/python/collections/list.md",
    "headings": [
      {
        "title": "Indexing và slicing",
        "id": "indexing-va-slicing"
      },
      {
        "title": "Khi nào không nên dùng list?",
        "id": "khi-nao-khong-nen-dung-list"
      },
      {
        "title": "Comprehension",
        "id": "comprehension"
      }
    ]
  },
  {
    "title": "Tuple trong Python",
    "description": "Dùng tuple cho nhóm giá trị có thứ tự, cấu trúc ổn định và có thể unpack.",
    "slug": "/collection/tuple",
    "category": "collections",
    "categoryLabel": "Collections",
    "order": 310,
    "difficulty": "beginner",
    "keywords": [
      "tuple python",
      "unpacking",
      "immutable",
      "namedtuple"
    ],
    "updated": "2026-09-18",
    "related": [
      "/collection/list",
      "/co-ban/kieu-du-lieu"
    ],
    "body": "Tuple là sequence immutable. Nó diễn đạt tốt một bản ghi nhỏ có cấu trúc cố định:\n\n```python\npoint = (10, 24)\nx, y = point\n```\n\nTuple có thể làm key của dict nếu mọi phần tử bên trong đều hashable. Dùng tuple để thể hiện “số lượng và thứ tự này là một phần của dữ liệu”, còn list khi collection cần thay đổi.\n\n## Unpacking an toàn\n\n```python\nfirst, *middle, last = [\"a\", \"b\", \"c\", \"d\"]\n```\n\nNếu bản ghi có nhiều trường và cần tên rõ nghĩa, `dataclass` thường dễ đọc hơn tuple vị trí.",
    "source": "content/python/collections/tuple.md",
    "headings": [
      {
        "title": "Unpacking an toàn",
        "id": "unpacking-an-toan"
      }
    ]
  },
  {
    "title": "Dictionary trong Python",
    "description": "Lưu dữ liệu theo cặp key-value, tra cứu nhanh và mô hình hóa record trong ứng dụng.",
    "slug": "/collection/dictionary",
    "category": "collections",
    "categoryLabel": "Collections",
    "order": 320,
    "difficulty": "beginner",
    "keywords": [
      "dictionary python",
      "dict",
      "key value",
      "mapping"
    ],
    "updated": "2026-09-18",
    "related": [
      "/collection/list",
      "/collection/set",
      "/co-ban/kieu-du-lieu"
    ],
    "body": "Dictionary ánh xạ key sang value. Dùng nó khi dữ liệu được truy cập bằng tên hoặc mã định danh thay vì vị trí.\n\n```python\nuser = {\"id\": 42, \"name\": \"An\", \"roles\": [\"editor\"]}\nuser[\"active\"] = True\n\nfor key, value in user.items():\n    print(key, value)\n```\n\n`dict.get(key, default)` hữu ích khi key có thể vắng mặt. Tránh dùng `if key in data` rồi truy cập lại nếu bạn chỉ cần lấy giá trị một lần.\n\nKey phải hashable, nên list không thể làm key nhưng tuple phù hợp nếu các phần tử của tuple cũng hashable.",
    "source": "content/python/collections/dictionary.md",
    "headings": []
  },
  {
    "title": "Set trong Python",
    "description": "Loại trùng và thực hiện phép hợp, giao, hiệu trên các tập phần tử.",
    "slug": "/collection/set",
    "category": "collections",
    "categoryLabel": "Collections",
    "order": 330,
    "difficulty": "beginner",
    "keywords": [
      "set python",
      "unique",
      "union",
      "intersection"
    ],
    "updated": "2026-09-18",
    "related": [
      "/collection/list",
      "/collection/dictionary"
    ],
    "body": "Set chứa các phần tử không trùng nhau và không nên được dùng khi thứ tự là dữ liệu quan trọng.\n\n```python\nfrontend = {\"alice\", \"minh\", \"lan\"}\nreviewers = {\"lan\", \"duy\"}\nboth = frontend & reviewers\nonly_frontend = frontend - reviewers\n```\n\nSet thường là lựa chọn tốt để kiểm tra membership nhiều lần hoặc loại trùng. Nếu cần giữ thứ tự xuất hiện và chỉ loại trùng, hãy cân nhắc `dict.fromkeys(items)`.",
    "source": "content/python/collections/set.md",
    "headings": []
  },
  {
    "title": "String trong Python",
    "description": "Làm việc với chuỗi, indexing, slicing, method, Unicode và f-string.",
    "slug": "/co-ban/string",
    "category": "strings",
    "categoryLabel": "Chuỗi",
    "order": 340,
    "difficulty": "beginner",
    "keywords": [
      "string python",
      "str",
      "f-string",
      "unicode",
      "encoding"
    ],
    "updated": "2026-09-18",
    "related": [
      "/co-ban/kieu-du-lieu",
      "/co-ban/bien",
      "/co-ban/toan-tu"
    ],
    "body": "String là sequence immutable của các ký tự Unicode. Bạn có thể index, slice và gọi method mà không làm thay đổi string gốc.\n\n```python\ncustomer = \"Nguyễn An\"\ndisplay = customer.strip().title()\nmessage = f\"Xin chào {display}\"\n```\n\n## Formatting\n\nƯu tiên f-string khi ghép giá trị vào câu. Với dữ liệu do người dùng nhập, xử lý và escape theo ngữ cảnh trước khi đưa vào HTML, SQL hoặc shell.\n\n## Encoding\n\nKhi đọc ghi file, nêu rõ encoding nếu dữ liệu đi qua nhiều hệ thống:\n\n```python\nfrom pathlib import Path\n\ncontent = Path(\"notes.txt\").read_text(encoding=\"utf-8\")\n```\n\n`encode()` chuyển string thành bytes; `decode()` chuyển bytes về string. Đừng nhầm byte length với số ký tự Unicode.",
    "source": "content/python/strings/string.md",
    "headings": [
      {
        "title": "Formatting",
        "id": "formatting"
      },
      {
        "title": "Encoding",
        "id": "encoding"
      }
    ]
  },
  {
    "title": "Hàm trong Python",
    "description": "Thiết kế hàm nhỏ, rõ contract với parameter, return value và type hint.",
    "slug": "/ham/function",
    "category": "functions",
    "categoryLabel": "Hàm",
    "order": 400,
    "difficulty": "beginner",
    "keywords": [
      "function python",
      "def",
      "return",
      "parameter",
      "argument"
    ],
    "updated": "2026-09-18",
    "related": [
      "/ham/scope",
      "/co-ban/bien",
      "/co-ban/kieu-du-lieu"
    ],
    "body": "Hàm đóng gói một thao tác có tên, đầu vào và đầu ra rõ ràng. Hàm tốt thường làm một việc và dễ gọi lại.\n\n```python\ndef calculate_total(subtotal: int, discount_rate: float = 0.0) -> int:\n    \"\"\"Return the rounded total after a percentage discount.\"\"\"\n    return round(subtotal * (1 - discount_rate))\n\ntotal = calculate_total(280_000, discount_rate=0.1)\n```\n\n## Parameter và argument\n\nParameter là tên trong định nghĩa; argument là giá trị khi gọi. Dùng keyword argument cho giá trị dễ gây nhầm, đặc biệt khi hàm có nhiều tham số cùng kiểu.\n\nTránh mutable default như `items=[]`; giá trị mặc định được tạo một lần khi định nghĩa hàm và có thể bị giữ lại giữa các lần gọi.",
    "source": "content/python/functions/function.md",
    "headings": [
      {
        "title": "Parameter và argument",
        "id": "parameter-va-argument"
      }
    ]
  },
  {
    "title": "Scope và LEGB",
    "description": "Hiểu phạm vi tên biến, closure và cách tránh phụ thuộc vào global state.",
    "slug": "/ham/scope",
    "category": "functions",
    "categoryLabel": "Hàm",
    "order": 410,
    "difficulty": "intermediate",
    "keywords": [
      "scope",
      "LEGB",
      "local global nonlocal",
      "closure"
    ],
    "updated": "2026-09-18",
    "related": [
      "/ham/function",
      "/ham/decorator"
    ],
    "body": "Python tìm tên theo thứ tự LEGB: Local, Enclosing, Global, Built-in. Khi đọc một tên, interpreter tìm từ phạm vi gần nhất ra ngoài.\n\n```python\ntax_rate = 0.08\n\ndef total_with_tax(amount: float) -> float:\n    return amount * (1 + tax_rate)\n```\n\nCode dựa vào global dễ khó kiểm thử. Ưu tiên truyền dependency qua parameter. `nonlocal` và `global` có chỗ dùng, nhưng nên hạn chế vì chúng làm thay đổi state bên ngoài hàm.\n\nClosure là hàm giữ lại giá trị từ enclosing scope. Decorator tận dụng cơ chế này để bọc hành vi mà không sửa body hàm gốc.",
    "source": "content/python/functions/scope.md",
    "headings": []
  },
  {
    "title": "Decorator",
    "description": "Bọc một hàm để thêm logging, đo thời gian hoặc policy mà không sửa logic chính.",
    "slug": "/ham/decorator",
    "category": "functions",
    "categoryLabel": "Hàm",
    "order": 420,
    "difficulty": "advanced",
    "keywords": [
      "decorator python",
      "wrapper",
      "functools wraps",
      "higher order function"
    ],
    "updated": "2026-09-18",
    "related": [
      "/ham/function",
      "/ham/scope",
      "/standard-library/functools"
    ],
    "body": "Decorator là callable nhận một callable khác và trả về callable mới. Dùng `functools.wraps` để giữ metadata của hàm gốc.\n\n```python\nfrom functools import wraps\n\ndef traced(function):\n    @wraps(function)\n    def wrapper(*args, **kwargs):\n        print(f\"calling {function.__name__}\")\n        return function(*args, **kwargs)\n    return wrapper\n\n@traced\ndef publish(title: str) -> None:\n    print(title)\n```\n\nDecorator phù hợp cho cross-cutting concern như logging, retry hoặc authorization. Đừng ẩn business rule quan trọng trong quá nhiều lớp wrapper; khi debug, sự trong suốt của call stack cũng là một tính năng.",
    "source": "content/python/functions/decorator.md",
    "headings": []
  },
  {
    "title": "Module và package",
    "description": "Tổ chức code Python thành module, package và import ổn định trong project.",
    "slug": "/module/module",
    "category": "modules",
    "categoryLabel": "Module & package",
    "order": 500,
    "difficulty": "beginner",
    "keywords": [
      "module python",
      "package",
      "import",
      "init py",
      "relative import"
    ],
    "updated": "2026-09-18",
    "related": [
      "/bat-dau/virtual-environment",
      "/oop/class-object",
      "/packaging/pyproject"
    ],
    "body": "Mỗi file `.py` là một module. Package gom các module liên quan thành một namespace có cấu trúc.\n\n```python\nfrom app.billing import calculate_total\n\ntotal = calculate_total(120_000)\n```\n\n## Import rõ ràng\n\nƯu tiên import tên cụ thể để đọc code biết dependency đến từ đâu. Tránh `from module import *` vì nó làm namespace khó đoán.\n\n`__name__ == \"__main__\"` cho phép một file vừa được import như module vừa chạy như script:\n\n```python\nif __name__ == \"__main__\":\n    main()\n```\n\nGiữ package dependency một chiều để tránh circular import. Nếu hai module biết quá nhiều về nhau, hãy tách abstraction chung.",
    "source": "content/python/modules/module.md",
    "headings": [
      {
        "title": "Import rõ ràng",
        "id": "import-ro-rang"
      }
    ]
  },
  {
    "title": "Exception và xử lý lỗi",
    "description": "Dùng try, except, raise và exception chaining để lỗi rõ nghĩa và có thể khôi phục.",
    "slug": "/exception",
    "category": "errors",
    "categoryLabel": "Exception",
    "order": 600,
    "difficulty": "intermediate",
    "keywords": [
      "exception python",
      "try except",
      "raise",
      "custom exception"
    ],
    "updated": "2026-09-18",
    "related": [
      "/file",
      "/ham/function",
      "/best-practices/error-handling"
    ],
    "body": "Exception diễn tả một điều kiện khiến luồng bình thường không thể tiếp tục. Bắt exception ở nơi bạn có đủ thông tin để xử lý hoặc thêm context.\n\n```python\ntry:\n    port = int(raw_port)\nexcept ValueError as error:\n    raise ValueError(\"PORT phải là một số nguyên\") from error\n```\n\nBắt exception cụ thể thay vì `except Exception` hoặc bare `except`. Nếu không thể khôi phục, hãy để lỗi nổi lên với message và context tốt.\n\n## else và finally\n\n`else` chạy khi không có exception; `finally` chạy dù thành công hay thất bại, phù hợp để dọn tài nguyên. Với file và lock, ưu tiên context manager để tránh quên cleanup.",
    "source": "content/python/errors/exception.md",
    "headings": [
      {
        "title": "else và finally",
        "id": "else-va-finally"
      }
    ]
  },
  {
    "title": "File, pathlib và context manager",
    "description": "Đọc ghi file an toàn với pathlib, encoding rõ ràng và khối with.",
    "slug": "/file",
    "category": "files",
    "categoryLabel": "File & IO",
    "order": 700,
    "difficulty": "beginner",
    "keywords": [
      "file python",
      "pathlib",
      "open",
      "read",
      "write",
      "context manager"
    ],
    "updated": "2026-09-18",
    "related": [
      "/exception",
      "/co-ban/string",
      "/module/module"
    ],
    "body": "`pathlib.Path` biểu diễn đường dẫn theo cách độc lập hệ điều hành. Dùng `with` để file luôn được đóng đúng cách.\n\n```python\nfrom pathlib import Path\n\nnotes = Path(\"data\") / \"notes.txt\"\nnotes.parent.mkdir(parents=True, exist_ok=True)\nnotes.write_text(\"Ship small changes.\\n\", encoding=\"utf-8\")\ncontent = notes.read_text(encoding=\"utf-8\")\n```\n\nVới file lớn, đọc từng dòng hoặc theo chunk thay vì nạp toàn bộ vào RAM. Khi xử lý đường dẫn do user cung cấp, kiểm tra scope cho phép và tránh để input trở thành đường dẫn tùy ý ra ngoài thư mục dữ liệu.",
    "source": "content/python/files/file.md",
    "headings": []
  },
  {
    "title": "Class và object",
    "description": "Mô hình hóa state và behavior bằng class, instance, method và dataclass.",
    "slug": "/oop/class-object",
    "category": "oop",
    "categoryLabel": "OOP",
    "order": 800,
    "difficulty": "intermediate",
    "keywords": [
      "class python",
      "object",
      "instance",
      "self",
      "dataclass"
    ],
    "updated": "2026-09-18",
    "related": [
      "/oop/inheritance",
      "/co-ban/kieu-du-lieu",
      "/module/module"
    ],
    "body": "Class là khuôn mô tả dữ liệu và hành vi; object là một instance cụ thể của class.\n\n```python\nfrom dataclasses import dataclass\n\n@dataclass(frozen=True)\nclass Money:\n    amount: int\n    currency: str = \"VND\"\n\n    def display(self) -> str:\n        return f\"{self.amount:,} {self.currency}\"\n```\n\n`self` là instance hiện tại. Hãy giữ invariant của object rõ ràng và hạn chế public mutable state nếu có nhiều rule cần bảo vệ.\n\nKhông phải mọi dữ liệu đều cần class. Với record đơn giản, dataclass gọn hơn; với logic thuần biến đổi input thành output, function thường dễ test hơn.",
    "source": "content/python/oop/class-object.md",
    "headings": []
  },
  {
    "title": "Inheritance và composition",
    "description": "Chọn giữa kế thừa và composition khi mô hình hóa hành vi mở rộng.",
    "slug": "/oop/inheritance",
    "category": "oop",
    "categoryLabel": "OOP",
    "order": 810,
    "difficulty": "intermediate",
    "keywords": [
      "inheritance python",
      "composition",
      "polymorphism",
      "super"
    ],
    "updated": "2026-09-18",
    "related": [
      "/oop/class-object",
      "/ham/decorator"
    ],
    "body": "Inheritance mô tả quan hệ “is-a”; composition mô tả “has-a”. Trong ứng dụng lớn, composition thường linh hoạt hơn vì bạn có thể thay collaborator mà không tạo cây class sâu.\n\n```python\nclass EmailNotifier:\n    def send(self, message: str) -> None:\n        print(f\"Email: {message}\")\n\nclass OrderService:\n    def __init__(self, notifier: EmailNotifier) -> None:\n        self.notifier = notifier\n```\n\nPolymorphism không nhất thiết cần inheritance: chỉ cần object cung cấp method mà consumer cần. Đây là tinh thần duck typing, nhưng interface nên được làm rõ bằng Protocol khi project lớn.",
    "source": "content/python/oop/inheritance.md",
    "headings": []
  },
  {
    "title": "Generator và yield",
    "description": "Xử lý stream dữ liệu theo kiểu lazy để giảm memory và diễn đạt pipeline rõ hơn.",
    "slug": "/advanced/generator",
    "category": "advanced",
    "categoryLabel": "Nâng cao",
    "order": 900,
    "difficulty": "advanced",
    "keywords": [
      "generator python",
      "yield",
      "lazy evaluation",
      "iterator"
    ],
    "updated": "2026-09-18",
    "related": [
      "/dieu-khien/for",
      "/async",
      "/collection/list"
    ],
    "body": "Generator function tạm dừng tại `yield` và tiếp tục khi consumer yêu cầu giá trị tiếp theo. Nó phù hợp với file lớn, cursor hoặc pipeline dữ liệu.\n\n```python\ndef non_empty_lines(lines):\n    for line in lines:\n        cleaned = line.strip()\n        if cleaned:\n            yield cleaned\n\nfor line in non_empty_lines([\"  deploy  \", \"\", \"monitor\"]):\n    print(line)\n```\n\nGenerator chỉ đi một chiều và chỉ chạy khi được consume. Nếu cần truy cập ngẫu nhiên hoặc lặp lại nhiều lần, list có thể phù hợp hơn. Đừng biến mọi logic thành generator chỉ vì nó “tiết kiệm memory”; hãy chọn theo lifetime dữ liệu.",
    "source": "content/python/advanced/generator.md",
    "headings": []
  },
  {
    "title": "async và await",
    "description": "Hiểu coroutine, event loop và khi nào asyncio giúp xử lý I/O đồng thời.",
    "slug": "/async",
    "category": "async",
    "categoryLabel": "Async",
    "order": 1000,
    "difficulty": "advanced",
    "keywords": [
      "async python",
      "await",
      "asyncio",
      "coroutine",
      "event loop",
      "task"
    ],
    "updated": "2026-09-18",
    "related": [
      "/advanced/generator",
      "/exception",
      "/typing"
    ],
    "body": "`async def` tạo coroutine function. `await` nhường quyền điều khiển trong lúc chờ một thao tác I/O, cho phép event loop phục vụ task khác.\n\n```python\nimport asyncio\n\nasync def refresh_cache() -> str:\n    await asyncio.sleep(0.1)  # mô phỏng I/O\n    return \"cache-ready\"\n\nasync def main() -> None:\n    result = await refresh_cache()\n    print(result)\n\nasyncio.run(main())\n```\n\nAsync không làm CPU-bound code tự nhiên nhanh hơn. Nếu một hàm blocking chạy trong event loop, nó chặn mọi task khác. Với nhiều thao tác I/O độc lập, `asyncio.gather` có thể chạy chúng đồng thời; hãy xử lý timeout, cancellation và exception một cách tường minh.",
    "source": "content/python/async/async-await.md",
    "headings": []
  },
  {
    "title": "Type hints hiện đại",
    "description": "Dùng annotation, TypedDict, Protocol và generic để làm rõ contract của code Python.",
    "slug": "/typing",
    "category": "typing",
    "categoryLabel": "Typing",
    "order": 1100,
    "difficulty": "intermediate",
    "keywords": [
      "type hints",
      "typing python",
      "TypedDict",
      "Protocol",
      "Generic",
      "Union"
    ],
    "updated": "2026-09-18",
    "related": [
      "/ham/function",
      "/oop/class-object",
      "/async"
    ],
    "body": "Type hint không thay đổi runtime semantics của Python, nhưng giúp IDE, type checker và người đọc hiểu contract.\n\n```python\nfrom collections.abc import Iterable\n\ndef total(values: Iterable[int]) -> int:\n    return sum(values)\n```\n\n## Chọn abstraction phù hợp\n\nDùng `TypedDict` cho mapping có schema cố định, `Protocol` cho interface dựa trên behavior, và generic khi một hàm bảo toàn mối quan hệ kiểu giữa input và output. Với Python hiện đại, `list[str]` và `str | None` thường dễ đọc hơn syntax cũ.\n\nType hint tốt vẫn cần test runtime: dữ liệu từ JSON, network hoặc user input không tự trở nên an toàn chỉ vì đã annotate.",
    "source": "content/python/typing/typing.md",
    "headings": [
      {
        "title": "Chọn abstraction phù hợp",
        "id": "chon-abstraction-phu-hop"
      }
    ]
  },
  {
    "title": "pip và dependency",
    "description": "Cài package, pin dependency và giữ môi trường Python tái lập được.",
    "slug": "/packaging/pip",
    "category": "packaging",
    "categoryLabel": "Packaging",
    "order": 1200,
    "difficulty": "beginner",
    "keywords": [
      "pip",
      "package",
      "dependency",
      "requirements",
      "pypi"
    ],
    "updated": "2026-09-18",
    "related": [
      "/bat-dau/virtual-environment",
      "/packaging/pyproject"
    ],
    "body": "`pip` là package installer phổ biến của Python. Luôn chạy qua interpreter đang dùng:\n\n```bash\npython -m pip install httpx\npython -m pip freeze > requirements.txt\n```\n\nTrong project mới, `pyproject.toml` thường là nơi tốt hơn để khai báo metadata và dependency. Pin phiên bản trực tiếp hoặc dùng lockfile theo công cụ của đội để build có thể tái lập.\n\nKhông cài package tùy tiện vào global Python. Review license, nguồn phát hành và quyền của dependency trước khi đưa vào production.",
    "source": "content/python/packaging/pip.md",
    "headings": []
  },
  {
    "title": "pyproject.toml",
    "description": "Vai trò của pyproject.toml trong build system, metadata và cấu hình công cụ Python.",
    "slug": "/packaging/pyproject",
    "category": "packaging",
    "categoryLabel": "Packaging",
    "order": 1210,
    "difficulty": "intermediate",
    "keywords": [
      "pyproject toml",
      "package",
      "wheel",
      "build system"
    ],
    "updated": "2026-09-18",
    "related": [
      "/packaging/pip",
      "/module/module"
    ],
    "body": "`pyproject.toml` là điểm cấu hình tiêu chuẩn cho nhiều công cụ Python: build backend, metadata package, lint, formatter và test.\n\n```toml\n[project]\nname = \"billing-service\"\nversion = \"0.1.0\"\nrequires-python = \">=3.12\"\ndependencies = [\"httpx>=0.27\"]\n```\n\nTách dependency chạy production khỏi dependency phát triển khi công cụ hỗ trợ. Khi publish wheel, kiểm tra file nào thực sự được đưa vào package và chạy test từ một môi trường sạch.",
    "source": "content/python/packaging/pyproject.md",
    "headings": []
  },
  {
    "title": "functools",
    "description": "Các công cụ chuẩn cho higher-order function, cache và thao tác callable.",
    "slug": "/standard-library/functools",
    "category": "standard-library",
    "categoryLabel": "Standard library",
    "order": 1300,
    "difficulty": "advanced",
    "keywords": [
      "functools",
      "lru_cache",
      "wraps",
      "partial",
      "reduce"
    ],
    "updated": "2026-09-18",
    "related": [
      "/ham/decorator",
      "/advanced/generator"
    ],
    "body": "`functools` chứa các tiện ích khi làm việc với callable. `wraps` giữ metadata khi viết decorator; `partial` cố định một phần argument; `lru_cache` memoize các hàm thuần với input hashable.\n\n```python\nfrom functools import lru_cache\n\n@lru_cache(maxsize=128)\ndef fibonacci(n: int) -> int:\n    if n < 2:\n        return n\n    return fibonacci(n - 1) + fibonacci(n - 2)\n```\n\nCache cần policy: dữ liệu có thay đổi không, key có thể tăng vô hạn không và khi nào cần invalidation. Đừng thêm cache trước khi đo đạc bottleneck.",
    "source": "content/python/standard-library/functools.md",
    "headings": []
  },
  {
    "title": "Best practice: error handling",
    "description": "Một số nguyên tắc để lỗi có context, log đúng chỗ và không che mất nguyên nhân thật.",
    "slug": "/best-practices/error-handling",
    "category": "best-practices",
    "categoryLabel": "Best practices",
    "order": 1400,
    "difficulty": "intermediate",
    "keywords": [
      "error handling",
      "logging",
      "best practices",
      "bare except"
    ],
    "updated": "2026-09-18",
    "related": [
      "/exception",
      "/file",
      "/typing"
    ],
    "body": "Lỗi tốt giúp người vận hành biết chuyện gì xảy ra, ở đâu và có thể làm gì tiếp theo. Hãy bắt exception gần boundary nơi bạn có thể thêm context hoặc trả response phù hợp.\n\n```python\ntry:\n    config = load_config()\nexcept OSError as error:\n    logger.exception(\"Không thể đọc cấu hình từ %s\", config_path)\n    raise RuntimeError(\"Ứng dụng không thể khởi động\") from error\n```\n\nKhông dùng bare `except`, không log rồi nuốt lỗi, và không đưa secret vào message. Ở boundary, chuyển lỗi nội bộ sang error code ổn định; trong core, giữ exception gốc để debug.",
    "source": "content/python/best-practices/error-handling.md",
    "headings": []
  },
  {
    "title": "assert và tư duy kiểm thử",
    "description": "Dùng assert để kiểm tra invariant trong development và xây chiến lược test đáng tin.",
    "slug": "/testing/assert",
    "category": "testing",
    "categoryLabel": "Testing",
    "order": 1500,
    "difficulty": "intermediate",
    "keywords": [
      "assert python",
      "testing",
      "invariant",
      "unittest",
      "pytest"
    ],
    "updated": "2026-09-18",
    "related": [
      "/ham/function",
      "/exception",
      "/typing"
    ],
    "body": "`assert condition` kiểm tra một giả định trong code. Khi giả định sai, Python ném `AssertionError`, giúp lỗi lộ ra gần nguyên nhân.\n\n```python\ndef split_total(total: int, parts: int) -> list[int]:\n    assert total >= 0\n    assert parts > 0\n    return [total // parts] * parts\n```\n\nAssert phù hợp cho invariant nội bộ, không phải để validate input không tin cậy hoặc thay thế kiểm thử. Khi chạy với tối ưu hóa, assertion có thể bị loại bỏ. Với hành vi cần đảm bảo ở production, hãy dùng điều kiện và exception rõ ràng.",
    "source": "content/python/testing/assert.md",
    "headings": []
  },
  {
    "title": "Đo và tối ưu hiệu năng",
    "description": "Bắt đầu từ số đo với timeit, profiler và lựa chọn cấu trúc dữ liệu đúng.",
    "slug": "/performance/profiling",
    "category": "performance",
    "categoryLabel": "Performance",
    "order": 1600,
    "difficulty": "advanced",
    "keywords": [
      "profiling",
      "performance",
      "timeit",
      "memory",
      "complexity"
    ],
    "updated": "2026-09-18",
    "related": [
      "/collection/list",
      "/advanced/generator",
      "/standard-library/functools"
    ],
    "body": "Tối ưu hiệu năng nên bắt đầu bằng câu hỏi “đo ở đâu?” thay vì đoán. `timeit` phù hợp cho micro-benchmark nhỏ; profiler phù hợp để tìm hot path trong chương trình thật.\n\n```python\nfrom timeit import timeit\n\nduration = timeit(\"sum(range(10_000))\", number=1_000)\nprint(f\"{duration:.3f}s\")\n```\n\nKiểm tra cả độ phức tạp và memory. List comprehension thường nhanh và rõ, nhưng generator giúp giảm memory khi pipeline lớn. Cache chỉ tốt khi hit rate, invalidation và giới hạn bộ nhớ đã được hiểu.",
    "source": "content/python/performance/profiling.md",
    "headings": []
  },
  {
    "title": "CPython, object model và bytecode",
    "description": "Cách nhìn đúng về CPython, object model và bytecode mà không đơn giản hóa sai.",
    "slug": "/internals/cpython",
    "category": "internals",
    "categoryLabel": "Python internals",
    "order": 1700,
    "difficulty": "advanced",
    "keywords": [
      "CPython",
      "bytecode",
      "object model",
      "reference counting",
      "garbage collection"
    ],
    "updated": "2026-09-18",
    "related": [
      "/co-ban/kieu-du-lieu",
      "/performance/profiling",
      "/async"
    ],
    "body": "CPython là một implementation của Python, không phải toàn bộ ngôn ngữ Python. Nó biên dịch source thành bytecode rồi thực thi qua virtual machine.\n\n```python\nimport dis\n\ndef add(left: int, right: int) -> int:\n    return left + right\n\ndis.dis(add)\n```\n\nChi tiết quản lý object, reference counting và cyclic garbage collection là đặc tính của CPython và có thể thay đổi theo phiên bản. GIL cũng không nên được mô tả như “Python không chạy song song”: I/O concurrency, multiprocessing và các extension nhả GIL tạo ra những trade-off khác nhau.",
    "source": "content/python/internals/cpython.md",
    "headings": []
  }
] as const;
export type Article = (typeof articles)[number];
export const articleBySlug = new Map(articles.map((article) => [article.slug, article]));
