import { readdir, readFile, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const contentRoot = path.join(root, "content", "python");
const generatedPath = path.join(root, "lib", "content.generated.ts");
const productionOrigin = "https://py.namgt.dev";

function walk(dir) {
  return readdir(dir, { withFileTypes: true }).then(async (entries) => {
    const nested = await Promise.all(entries.map((entry) => {
      const next = path.join(dir, entry.name);
      return entry.isDirectory() ? walk(next) : entry.name.endsWith(".md") ? [next] : [];
    }));
    return nested.flat();
  });
}

function parseValue(value) {
  const trimmed = value.trim();
  if (trimmed.startsWith("[")) {
    try { return JSON.parse(trimmed); } catch { return trimmed.slice(1, -1).split(",").map((item) => item.trim().replace(/^['"]|['"]$/g, "")).filter(Boolean); }
  }
  if (trimmed.startsWith("{")) return JSON.parse(trimmed);
  if (trimmed === "true") return true;
  if (trimmed === "false") return false;
  if (/^-?\d+(\.\d+)?$/.test(trimmed)) return Number(trimmed);
  return trimmed.replace(/^['"]|['"]$/g, "");
}

function parseMarkdown(raw, filePath) {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) throw new Error(`Missing frontmatter: ${filePath}`);
  const frontmatter = {};
  for (const line of match[1].split(/\r?\n/)) {
    const separator = line.indexOf(":");
    if (separator < 1) continue;
    frontmatter[line.slice(0, separator).trim()] = parseValue(line.slice(separator + 1));
  }
  const required = ["title", "description", "slug", "category", "order", "difficulty", "keywords", "updated"];
  for (const key of required) if (!(key in frontmatter)) throw new Error(`Missing ${key} in ${filePath}`);
  if (!Array.isArray(frontmatter.keywords)) throw new Error(`keywords must be an array in ${filePath}`);
  if (!frontmatter.slug.startsWith("/")) throw new Error(`slug must start with / in ${filePath}`);
  return { ...frontmatter, body: match[2].trim(), source: path.relative(root, filePath).replaceAll("\\", "/") };
}

function headingId(text) {
  return text.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9\s-]/g, "").trim().replace(/\s+/g, "-");
}

const files = await walk(contentRoot);
const articles = (await Promise.all(files.map(async (file) => {
  const article = parseMarkdown(await readFile(file, "utf8"), file);
  const headings = [...article.body.matchAll(/^#{2,3}\s+(.+)$/gm)].map((match) => ({ title: match[1].trim(), id: headingId(match[1]) }));
  return { ...article, headings };
}))).sort((a, b) => a.order - b.order);

const slugs = new Set();
for (const article of articles) {
  if (slugs.has(article.slug)) throw new Error(`Duplicate slug: ${article.slug}`);
  slugs.add(article.slug);
  const ids = new Set();
  for (const heading of article.headings) {
    if (ids.has(heading.id)) throw new Error(`Duplicate heading id ${heading.id} in ${article.slug}`);
    ids.add(heading.id);
  }
  for (const related of article.related ?? []) if (!articles.some((item) => item.slug === related)) throw new Error(`Broken related link ${related} in ${article.slug}`);
}

const bodyLinks = /\]\((\/[a-z0-9\-/]+)(?:#[^)]+)?\)/g;
for (const article of articles) {
  for (const match of article.body.matchAll(bodyLinks)) if (!slugs.has(match[1])) throw new Error(`Broken internal link ${match[1]} in ${article.slug}`);
}

await mkdir(path.dirname(generatedPath), { recursive: true });
await writeFile(generatedPath, `// Generated by scripts/generate-content.mjs. Do not edit by hand.\nexport const articles = ${JSON.stringify(articles, null, 2)} as const;\nexport type Article = (typeof articles)[number];\nexport const articleBySlug = new Map<string, Article>(articles.map((article): [string, Article] => [article.slug, article]));\n`);
await mkdir(path.join(root, "public"), { recursive: true });
await writeFile(path.join(root, "public", "sitemap.xml"), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${["/", ...articles.map((article) => article.slug)].map((slug) => `  <url><loc>${productionOrigin}${slug}</loc></url>`).join("\n")}\n</urlset>\n`);
await writeFile(path.join(root, "public", "robots.txt"), `User-agent: *\nAllow: /\nSitemap: ${productionOrigin}/sitemap.xml\n`);
console.log(`Generated ${articles.length} articles, search data, sitemap.xml and robots.txt.`);
